# Generated by Django 5.0.2 on 2024-03-04 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
    ]
