# Generated by Django 5.0.2 on 2024-03-04 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_learning', '0003_topic_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='owner',
            new_name='ownerASDF1',
        ),
    ]
