# Generated by Django 5.0.2 on 2024-03-04 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_learning', '0004_rename_owner_topic_ownerasdf1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='ownerASDF1',
        ),
    ]
